name: "Test"

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NIX_PATH: https://github.com/nixos/nixpkgs/archive/nixpkgs-unstable.tar.gz
    steps:
      - uses: cachix/install-nix-action@v16
      - uses: actions/checkout@v2
      - run: make
